environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  - "%PYTHON%\\python.exe -m pip install altgraph"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
